package com.fiiiiive.zippop.global.base;

public enum BaseStatus {

        ROLE_CUSTOMER, ROLE_COMPANY,

        GOODS_STOCK, GOODS_RESERVED,

        RESERVE_READY, STOCK_READY, RESERVE_DELIVERY, STOCK_DELIVERY, RESERVE_CANCEL, STOCK_CANCEL, STOCK_COMPLETE, RESERVE_COMPLETE,

        COMPLETE, INCOMPLETE,

        STORE_START, STORE_END,

}
