package com.fiiiiive.zippop.global.base;

import lombok.Getter;

@Getter
public enum ServiceErrorCode {
    USER_NOT_FOUND(308, "계정을 찾을 수 없습니다."),
    CACHE_FAIL_NOT_FOUND(999, "예약을 하지 않은 사용자입니다."),
    AUTH_LOGIN_FAIL_ID_NULL(1001, "아이디를 입력해주세요."),
    AUTH_LOGIN_FAIL_PASSWORD_NULL(1002, "비밀번호를 입력해주세요."),
    AUTH_LOGOUT_FAIL(1007, "로그아웃에 실패했습니다."),
    AUTH_SIGNUP_FAIL_ALREADY_REGISTER_AS_CUSTOMER(2002, "이미 고객 회원으로 가입된 계정입니다. 고객 회원은 기업 회원으로 회원가입 할 수 없습니다."),
    AUTH_SIGNUP_FAIL_ALREADY_REGISTER_AS_COMPANY(2003, "이미 기업 회원으로 가입된 계정입니다. 기업 회원은 고객 회원으로 회원가입할 수 없습니다."),
    AUTH_SIGNUP_FAIL_ALREADY_EXIST(2004, "이미 회원가입한 계정입니다."),
    AUTH_SIGNUP_FAIL_ALREADY_EXIST_ID(2023, "이미 존재하는 아이디입니다."),
    AUTH_SIGNUP_FAIL_INVALID_ROLE_TYPE(2025, "유효하지 않은 사용자 타입입니다."),
    AUTH_SIGNUP_FAIL_INVALID_ROLE(2026, "해당 계정 타입에 맞지 않는 역할입니다."),
    AUTH_VERIFY_FAIL(2005, "이메일 인증에 실패했습니다."),
    AUTH_INACTIVE_FAIL(2007, "계정 비활성화에 실패했습니다."),
    AUTH_ACTIVE_FAIL(2009, "계정 활성화에 실패했습니다."),
    AUTH_ACTIVE_FAIL_NOT_INACTIVE(2010, "활성화된 계정입니다. 계정정보는 ID/PW 찾기를 이용하세요"),
    AUTH_FIND_ID_FAIL_NOT_EMAIL_VERIFY(2011, "이메일 인증이 되지않은 사용자는 아이디 찾기를 진행할 수 없습니다."),
    AUTH_FIND_ID_FAIL_NOT_EXIST(2012, "해당 이름과 전화번호로 가입된 아이디가 존재하지 않습니다."),
    AUTH_FIND_PW_FAIL_NOT_EMAIL_VERIFY(2014, "이메일 인증이 되지않은 사용자는 비밀번호 찾기를 진행할 수 없습니다."),
    AUTH_FIND_PW_FAIL_NOT_EXIST(2015, "해당 아이디와 이메일로 가입된 계정이 존재하지 않습니다."),
    AUTH_EDIT_INFO_FAIL(2017, "계정 프로필 정보 변경에 실패했습니다."),
    AUTH_EDIT_INFO_FAIL_NOT_FOUND_MEMBER(2018, "사용자를 찾을 수 없습니다."),
    AUTH_RESET_PW_FAIL(2020, "계정 비밀번호 변경에 실패했습니다."),
    AUTH_RESET_PW_FAIL_NOT_FOUND_MEMBER(2021, "사용자를 찾을 수 없습니다."),
    AUTH_RESET_PW_FAIL_PASSWORD_NOT_MATCH(2022, "계정 비밀번호가 틀립니다."),
    AUTH_GET_PROFILE_FAIL(2022, "프로필 조회에 실패했습니다"),
    CART_REGISTER_FAIL_GOODS_NOT_FOUND(3002, "상품을 찾을 수 없습니다."),
    CART_REGISTER_FAIL_STORE_NOT_FOUND(3003, "상품을 찾을 수 없습니다."),
    CART_REGISTER_FAIL_ITEM_EXIST(3004, "해당 상품이 이미 장바구니에 존재 합니다."),
    CART_SEARCH_ALL_FAIL_NOT_FOUND(3006, "장바구니 목록을 찾을 수 없습니다."),
    CART_ITEM_SEARCH_ALL_FAIL_NOT_FOUND(3008, "장바구니 아이템 목록을 찾을 수 없습니다."),
    CART_ITEM_COUNT_FAIL_NOT_FOUND(3010, "장바구니 아이템을 찾을 수 없습니다."),
    CART_ITEM_COUNT_FAIL_IS_ZERO(3011, "장바구니 아이템의 수량은 한개 이상입니다."),
    CART_DELETE_ALL_FAIL_NOT_FOUND(3014, "장바구니를 찾을 수 없습니다."),
    CART_DELETE_ALL_FAIL_UNAUTHORIZED(3015, "해당 장바구니의 소유자가 아닙니다."),
    STORE_REGISTER_FAIL_UNAUTHORIZED(4001, "팝업 스토어 등록은 기업회원만 가능합니다."),
    STORE_SEARCH_FAIL_NOT_FOUND(4003, "해당 팝업 스토어가 존재하지 않습니다."),
    STORE_SEARCH_ALL_FAIL_NOT_FOUND(4005, "해당 팝업 스토어가 조재하지 않습니다."),
    STORE_UPDATE_FAIL_NOT_FOUND(4007, "팝업 스토어를 찾을 수 없습니다."),
    STORE_DELETE_FAIL_NOT_FOUND(4010, "팝업 스토어를 찾을 수 없어 삭제에 실패했습니다."),
    STORE_OWN_FAIL_INVALID_MEMBER(4008, "해당 팝업스토어를 등록한 기업회원이 아닙니다."),
    STORE_LIKE_FAIL_NOT_FOUND(4013, "해당 팝업 스토어를 찾을 수 없습니다."),
    STORE_LIKE_FAIL_INVALID_MEMBER(4014, "인증되지않은 사용자는 좋아요 기능이 제한됩니다."),
    STORE_LIKE_SEARCH_ALL_FAIL_NOT_FOUND(4016, "팝업 스토어 좋아요 목록을 찾을 수 없습니다."),
    STORE_REVIEW_FAIL_INVALID_ROLE(4019, "기업 회원은 리뷰 작성 기능이 제한 됩니다."),
    STORE_REVIEW_FAIL_INVALID_MEMBER(4020, "해당 팝업 스토어에서 결제한 내역이 없습니다."),
    STORE_REVIEW_FAIL_NOT_FOUND(4021, "해당 팝업 스토어를 찾을 수 없습니다."),
    STORE_REVIEW_FAIL_DUPLICATED(4022, "리뷰는 팝업스토어당 한 글씩만 적을 수 있습니다."),
    STORE_REVIEW_SEARCH_ALL_FAIL_NOT_FOUND(4024, "팝업 스토어 리뷰 목록을 찾을 수 없습니다."),
    GOODS_REGISTER_FAIL_NOT_FOUND_STORE(5001, "해당 스토어를 찾을 수 없습니다."),
    GOODS_REGISTER_FAIL_INVALID_MEMBER(5002, "팝업 굿즈 등록은 팝업 스토어를 등록한 기업회원만 가능합니다."),
    GOODS_SEARCH_FAIL_NOT_FOUND_STORE(5004, "해당 스토어를 찾을 수 없습니다."),
    GOODS_SEARCH_ALL_FAIL_STORE_NOT_NOT_FOUND(5006, "해당 스토어를 찾을 수 없습니다."),
    GOODS_UPDATE_FAIL_NOT_FOUND(5008, "팝업 굿즈를 찾을 수 없습니다."),
    GOODS_UPDATE_FAIL_NOT_FOUND_INVALID_MEMBER(5009, "팝업 굿즈 수정은 팝업 스토어를 등록한 기업회원만 가능합니다."),
    GOODS_DELETE_FAIL_NOT_FOUND(5011, "팝업 스토어를 찾을 수 없어 삭제에 실패했습니다."),
    GOODS_DELETE_FAIL_INVALID_MEMBER(5012, "해당 팝업 스토어를 등록한 기업 회원이 아닙니다."),
    GOODS_REGISTER_FAIL_INVALID_STATUS(5013, "유효하지 않은 상태값 입니다."),
    ORDERS_PAY_FAIL(6001, "결제에 실패했습니다."),
    ORDERS_PAY_FAIL_INVALID_ROLE(6002, "기업회원은 결제를 진행할 수 없습니다."),
    ORDERS_PAY_FAIL_NOT_FOUND_MEMBER(6003, "결제 정보에 해당하는 유저가 없습니다."),
    ORDERS_PAY_FAIL_NOT_FOUND_GOODS(6004, "결제 정보에 해당하는 팝업 굿즈가 없습니다."),
    ORDERS_PAY_FAIL_LIMIT_EXCEEDED(6005, "사전 예매 굿즈는 품목 당 하나만 구매 가능합니다."),
    ORDERS_PAY_FAIL_LIMIT_AMOUNT(6006, "재고 수량보다 많은 수량을 결제할 수 없습니다."),
    ORDERS_PAY_FAIL_POINT_EXCEEDED(6006, "3000포인트 이상부터 사용할 수 있습니다."),
    ORDERS_PAY_FAIL_INVALID_TOTAL_PRICE(6007, "결제 금액이 잘못되었습니다."),
    ORDERS_CANCEL_FAIL_INVALID_ROLE(6009, "기업회원은 요청할 수 없는 API 입니다."),
    ORDERS_CANCEL_FAIL_NOT_FOUND_MEMBER(6010, "결제 정보에 해당하는 유저가 없습니다."),
    ORDERS_CANCEL_FAIL_NOT_FOUND(6011, "해당 결재내역을 찾을 수 없습니다."),
    ORDERS_CANCEL_FAIL_ALREADY_CANCEL(6012, "이미 환불 처리가 진행된 내역입니다."),
    ORDERS_CANCEL_FAIL_NOT_FOUND_GOODS(6013, "결제 정보에 해당하는 팝업 굿즈가 없습니다."),
    ORDERS_CANCEL_FAIL_IS_DELIVERY(6014, "배송 중인 건에 대해선 환불을 지원하지 않습니다."),
    ORDERS_COMPLETE_FAIL_INVALID_MEMBER(6017, "해당 거래내역에 접근 권한이 없습니다."),
    ORDERS_COMPLETE_FAIL_IS_DELIVERY(6018, "이미 주문 확정 처리 되고 배달 중입니다."),
    ORDERS_COMPLETE_FAIL_NOT_FOUND(6019, "거래 내역을 찾을 수 없습니다."),
    ORDERS_COMPLETE_FAIL_IS_CANCEL(6020, "결제 취소 건에 대해선 주문 확정을 지원하지 않습니다."),
    ORDERS_SEARCH_FAIL_NOT_FOUND(6022, "거래 내역을 찾을 수 없습니다."),
    ORDERS_SEARCH_FAIL_INVALID_MEMBER(6023, "해당 거래내역에 접근 권한이 없습니다."),
    ORDERS_SEARCH_FAIL_NOT_FOUND_STORE(6024, "팝업 스토어를 찾을 수 없습니다"),
    ORDERS_SEARCH_ALL_FAIL_NOT_FOUND(6026, "거래 내역을 찾을 수 없습니다."),
    ORDERS_SEARCH_ALL_FAIL_NOT_FOUND_STORE(6027, "팝업 스토어를 찾을 수 없습니다"),
    ORDERS_SEARCH_ALL_FAIL_INVALID_MEMBER(6028, "해당 거래내역에 접근 권한이 없습니다."),
    RESERVE_REGISTER_FAIL_INVALID_MEMBER(7001, "해당 팝업 스토어의 관리자가 아닙니다."),
    RESERVE_REGISTER_FAIL_INVALID_ROLE(7002, "기업 회원이 아닌 회원은 예약을 생성할 수 없습니다."),
    RESERVE_REGISTER_FAIL_TIME_CLOSED(7003, "해당 시간대는 예약이 마감되었습니다."),
    RESERVE_REGISTER_FAIL_LIMIT_EXCEEDED(7003, "팝업 스토어의 총 예약 인원수를 초과합니다."),
    RESERVE_REGISTER_FAIL_NOT_FOUND_STORE(7004, "해당 팝업 스토어를 찾을 수 없습니다."),
    RESERVE_REGISTER_FAIL_STORE_ENDED(7005, "종료된 팝업 스토어는 예약을 생성할 수 없습니다."),
    RESERVE_ENROLL_FAIL_NOT_FOUND(7006, "생성된 예약을 찾을 수 없습니다."),
    RESERVE_ENROLL_FAIL_INVALID_ROLE(7007, "기업 회원은 예약에 참여할 수 없습니다."),
    RESERVE_SEARCH_ALL_FAIL_NOT_FOUND(7009, "해당 예약을 찾을 수 없습니다."),
    RESERVE_CANCEL_FAIL(7009, "예약 취소에 실패했습니다."),
    RESERVE_SEARCH_STATUS_FAIL_NOT_FOUND(7011, "예약을 조회할 수 없습니다."),
    RESERVE_ACCESS_FAIL(7013, "유효하지 않은 사용자입니다."),
    RESERVE_DELETE_FAIL_NOT_FOUND_STORE(7015, "해당 팝업 스토어를 찾을 수 없습니다."),
    RESERVE_DELETE_FAIL_INVALID_MEMBER(7016, "해당 팝업 스토어의 소유자가 아닙니다."),
    RESERVE_DELETE_FAIL_NOT_FOUND(7017, "해당 예약을 찾을 수 없습니다."),
    RESERVE_DELETE_FAIL_END_TIME(7018, "종료된 팝업 예약은 삭제할 수 없습니다."),
    PAYOUT_SEARCH_FAIL_NOT_FOUND(8001, "팝업 스토어 정산 내역을 찾을 수 없습니다."),
    PAYOUT_SEARCH_FAIL_NOT_FOUND_STORE(8002, "팝업 스토어 정산 내역을 찾을 수 없습니다."),
    PAYOUT_SEARCH_FAIL_INVALID_MEMBER(8003, "해당 팝업 스토어의 관리자가 아닙니다.");

    private final Integer code;
    private final String message;

    ServiceErrorCode(Integer code, String message) {
        this.code = code;
        this.message = message;
    }
}
